version: '3'
services:
  jenkins-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_DOCKER_PATH}:/usr/bin/docker
  jenkins-cli:
    build:
      context: .
      dockerfile: CLIDockerfile
    depends_on:
      - jenkins-server
volumes:
  jenkins_home:
