version: '3'
services:
  jenkins:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_DOCKER_PATH}:/usr/bin/docker
volumes:
  jenkins_home:
